### ISSUE TITLE
OOBE hangs on finalizing device setup

### ISSUE THREAD

**Issue by cmajane** [microsoft/Azure-Percept-Private-Preview#163]
After the final step of the OOBE (entering device name, checking TPM enrollment, and hitting Next), the device setup hangs on the screen below and never completes. 

![image](https://user-images.githubusercontent.com/80842389/111498594-75305a00-8718-11eb-892a-4d0cab387339.png)

The new device name then appears in the IoT hub, but displays the following IoT Edge Runtime Response error: 406 -- The device is offline or not sending status reports.

**Comment by v-iskha** [comment]
@cmajane - Please refer steps from [OOBE](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/oobe.md) guide and let us know if this helps.

**Comment by cmajane** [comment]
I have followed the OOBE guide several times and always encounter this issue after step 13 of the OOBE procedure.

**Comment by mikelor** [comment]
@cmajane, there are some helpful tips in the [Notes](https://github.com/microsoft/Project-Santa-Cruz-Preview/blob/main/user-guides/getting_started/oobe.md#notes) section of OOBE.

Another thing to look into...
  1. What type of WiFi Access Point are you pointing your DevKit to? I've found that a Mobile Network or an "enterprisey" type network will not always succeed. I usually have more success with my "consumer" grade (asus/comcast) WAP.

**Comment by v-iskha** [comment]
@EthanChangAED - After the final step of the OOBE (entering device name, checking TPM enrollment, and hitting Next), the device setup hangs and never completes.

**Comment by v-iskha** [comment]
@WendyAnn0079 - After the final step of the OOBE (entering device name, checking TPM enrollment, and hitting Next), the device setup hangs and never completes.

**Comment by v-iskha** [comment]
@cmajane - Just following up to see if you are still facing any issue on OOBE.

**Comment by v-iskha** [comment]
@cmajane - Since there is no response, we assume the issue to be resolved. Please email "aedppsup@microsoft.com" if you still need support on this issue.
