### ISSUE TITLE
Pasting ssh public key with linebreaks in oobe creates broken user account

### ISSUE THREAD

**Issue by holgerkenn** [microsoft/Azure-Percept-Private-Preview#179]
Repro:
1. In oobe, create user with ssh public key, select "Use existing public key"
2. To enter public key, open e.g. WSL window and type "cat .ssh/id_rsa.pub", then mark public key in terminal window and rightclick to copy (this now includes line breaks in the copy)
3. Paste key into OOBE public key window and submit.
Error message:
Error
Command failed: ssh-keygen -l -f /home/<username>/.ssh/id_rsa.pub /home/<username>/.ssh/id_rsa.pub is not a public key file.

Trying to correct the issue via "Back" and resubmit yields another error:
Error
User "<username>" already exists on the system

adu-version: 2021.101.106.118

**Comment by v-iskha** [comment]
@WendyAnn0079 - User is having some issues at OOBE level. Please advise.

**Comment by v-iskha** [comment]
@SillyKeith - Hi Keith, need your expertise on this issue. Pasting SSH public key with linebreaks in OOBE created broken user account.

**Comment by SillyKeith** [comment]
Thank you for reporting this. 

After you issue the cat command `cat .ssh/id_rsa.pub`, How much of the text blob are you copying?  Do you stop highlighting at the end of your "<username>"?   

- When i tested this with Windows Terminal (Ubuntu 20.04) - the act of highlighting copies the text and **this worked.**
- When I tested with WSL command window (Ubuntu 20.04) - Highlighting only the text and nothing else, then clicked copy, this worked and did not include a line return..
- Tested the same WSL window doing Edit, Mark, Edit Copy - also worked and did not include the line return.

Example full key format:  copying only the text in quotes
_"ssh-rsa <your key> <username>"_

I was unable to get a line return but was able to repro a failure when I only copied and used the _<your key>_ portion.

**Comment by holgerkenn** [comment]
This seems to have been triggered by Windows Terminal issue. After upgrading Windows Terminal to 1.7.1033.0, the copied text does not contain line breaks anymore. So that part cannot be repro'd anymore.

Having said that, I think the underlying issue is in Percept and it is not fixed. If you insert artificial line breaks into the key, the form validation should then not accept it as a ssh public key. So the issue is actually the way the public key is validated since it seems to pass some validation but then breaks the key parsing of ssh-keygen and creates a broken user account while the oobe continues. In my opinion, expected behavior would be to not create the user and send back the user to the previous oobe step to enter a new key.

**Comment by SillyKeith** [comment]
Absolutely agree and I've filed a bug on these two items.

- text input validation 
- any errors in the SSH user creation process should result in "no user created".

**Comment by v-iskha** [comment]
@SillyKeith - Any updates on the bugs filed on this issue. Do you want to keep this ticket open?

**Comment by SillyKeith** [comment]
We have added extra validation steps and will not create user accounts when errors occur.   These changes will be present in the July release.
