### ISSUE TITLE
Add Note/Link To "Collect your device’s TPM-derived SoftAP password" before beginning update procedure

### ISSUE THREAD

**Issue by mikelor** [microsoft/Azure-Percept-Private-Preview#189]
Congratulations on the release of the new firmware. I successfully updated my DevKit.

For those users who may not be familiar (or lost their / misplaced their access points secret password), please include a link on the new Update Instructions to [Collect your device’s TPM-derived SoftAP password](https://github.com/microsoft/Azure-Percept-Private-Preview/tree/main/tools/SoftAP-access-info-tool) as a pre-requisite to the update. This will save users who may not realize their access point and password will change after this update.

For example my access point changed from
  * scz-xxxx
  * apd-xxxx

**Comment by mimcco** [comment]
Thanks @mikelor! Can you do me a quick favor and fill out this really short survey. It is how we are tracking who has completed the update, and will help prevent us from sending you any nag mails :). Plus we'd love your feedback.

**Comment by mikelor** [comment]
@mimcco done!

**Comment by v-iskha** [comment]
We have now implemented the info in the pre-requisite of device update. Thanks @mikelor for suggestion
