### ISSUE TITLE
Unable to Collect Device’s TPM-derived SoftAP password (Pre 11/17/2020 Device)

### ISSUE THREAD

**Issue by mikelor** [microsoft/Azure-Percept-Private-Preview#190]
I'm attempting to update a device that was shipped before 11/17/2020.  When I try and run the 
`./scz-tool-wifisoftap-accessinfo.devkit.sh` script as defined on this page [Collect your device’s TPM-derived SoftAP password](https://github.com/microsoft/Azure-Percept-Private-Preview/tree/main/tools/SoftAP-access-info-tool), it does not return. The script simply hangs and does not finish.

Will my Access Point Pre-Shared Key change from it's default with this firmware update? Please note this DevKit is an pre-11/17/2020 device and no Access Point / Pre-Shared Key Sticker was included. It uses the initial default values.

I'm holding off updating this device until I receive an answer. Thanks.

**Comment by v-iskha** [comment]
@mikelor - Have you tried running sudo before the command like sudo ./scz-tool-wifisoftap-accessinfo.devkit.sh -m=pe101

Also if you have older device then your command will be sudo ./scz-tool-wifisoftap-accessinfo.devkit.sh -m=pe100

**Comment by mikelor** [comment]
Thanks @v-iskha I ran as root, so no sudden needed. I did try p100 switch same problem.

I just really need to no if my access point and pre shared key is expected to change after the latest firmware.

**Comment by v-iskha** [comment]
@mikelor - After updating, your device will be reset to factory settings and you will lose your Wi-Fi connection (for sometime), SSH login and pre-shared key. Also Wi-Fi access point might change from scz-xxxx to apd-xxxx (where “xxxx” is the last four digits of the dev kit’s MAC address). Once the update is completed you can always reconfigure your device using OOBE.

**Comment by mikelor** [comment]
Thanks @v-iskha will the pre-shared key change?

**Comment by v-iskha** [comment]
@mikelor - Let me confirm on this.
@SillyKeith - Do you know if pre-shared key will get changed after device is updated? My understanding is that it should get reset and can be recovered by login as root and performing steps from [Collect your device’s TPM-derived SoftAP password](https://github.com/microsoft/Azure-Percept-Private-Preview/tree/main/tools/SoftAP-access-info-tool)

**Comment by SillyKeith** [comment]
The SoftAP password (Pre-shared key) does not change from flashing as it's derived from the TPM.   The only thing I can think of that would cause the script to hang is if  a:) The download was corrupt - try redoing the wget.   or  b:)  The TPM can't be found- run this command to see if it's there:   ```
[ -d $(ls -d /sys/kernel/security/tpm* 2>/dev/null | head -1) ] && echo "TPM available" \
    || echo "TPM missing"
```

**Comment by SillyKeith** [comment]
Glad it finally worked!  Thank you for letting us know.
