### ISSUE TITLE
Can't deploy customvision.ai model on Percept dev kit using percept studio

### ISSUE THREAD

**Issue by Benoit-LdL** [microsoft/Azure-Percept-Private-Preview#191]
I made a custom object detection model on CustomVision.ai.
I have a Microsoft Percept Dev kit and would like to deploy my custom model on it.

After selecting my CustomVision project and the correct iteration in the Percept Studio a notification tells me it has been deployed correctly.

When checking the logs from the modules on the Percept device I see no problems on the edgeAgent logs (except the fact that it tries to restart the azureeyemodule constantly).

the logs from the azureeyemodule do give some more information:

-----------

F: [global] [ 745711] [Scheduler00Thr] dispatcherLocalEventGetResponse:128 local NACK RTS. stream 'InferenceStream4' is full (event 10141)

W: [global] [ 745711] [Scheduler00Thr] dispatcherLocalEventGetResponse:132 Blocked event would cause dispatching thread to wait on semaphore infinitely

terminate called after throwing an instance of 'std::logic_error'
what(): Network with multiple outputs is not provided with output names!
Expected names: raw_boxes, raw_probs
F: [global] [ 745733] [Scheduler00Thr] dispatcherLocalEventGetResponse:128 local NACK RTS. stream 'InferenceStream4' is full

-----------

after these lines the module restarts and repeats itself.
Here you can find the support-bundle I created after the errors occured (you can find a good error example starting at line 3750 in the azureeyemodule_log.txt): [support_bundle.zip](https://github.com/microsoft/Azure-Percept-Private-Preview/files/6404964/support_bundle.zip)

**Comment by v-prsasa** [comment]
@Benoit-LdL  Have you updated your dev kit to the latest software? These updates have numerous fixes that improve the reliability and security of the device.

**Comment by Benoit-LdL** [comment]
as far as I know I did yes, I have reset the device several times so it has reinstalled the different modules several times. How can I check if I'm running the latest version?

**Comment by v-prsasa** [comment]
@Benoit-LdL Confirm the update by navigating to the devkit's Device Twin in IoT Hub and checking the value of swVersion.

**Comment by Benoit-LdL** [comment]
this is the version: "swVersion": {"value": "2020.110.114.105"

**Comment by v-prsasa** [comment]
@Benoit-LdL Could you please update your device via USB. Here is the link for reference -https://docs.microsoft.com/en-gb/azure/azure-percept/how-to-update-via-usb

**Comment by Benoit-LdL** [comment]
After the update i'm still facing the same issue

-------

W: [global] [    372551] [Scheduler00Thr] dispatcherLocalEventGetResponse:132   Blocked event would cause dispatching thread to wait on semaphore infinitely

2021-04-30 14:02:52 RTSP buffer pushed to result with timestamp 2800 (ms)
terminate called after throwing an instance of 'std::logic_error'
  what():  Network with multiple outputs is not provided with output names!
Expected names: raw_boxes, raw_probs
percept@apd-d8c0a658d84b [ ~ ]$

-------

**Comment by v-prsasa** [comment]
@Benoit-LdL Did you try rebooting the device and try again?

**Comment by Benoit-LdL** [comment]
I did yes, I'm trying to make a new support-bundle but it seems to be stuck at calling iotedge check

**Comment by v-prsasa** [comment]
@Benoit-LdL Can you perform the below steps and let us know the outcome.
Go to IoT Hub -> IoT Edge -> Select Device -> click on Set Modules -> select azureyemodule, 
then change image uri to mcr.microsoft.com/azureedgedevices/azureeyemodule:2103-2 
and click update -> click on Review + create -> click on create. 
 
The module download will get initiated. To verify if the download is completed, click on Azureeyemodule and check if the reported value is same as desired value.
 
 
Note: For issues wherein the device is not connecting to IoT Hub, you will have to go thru OOBE first and then go thru the above steps to upgrade the azureyeemodule which will ensure the sample model deployment works

**Comment by Benoit-LdL** [comment]
this made it work, thanks for the help!
