### ISSUE TITLE
Dev-Tools-Pack vundefined error

### ISSUE THREAD

**Issue by saseiler** [microsoft/Azure-Percept-Private-Preview#192]
installer version: undefined
  env:
  ```
  os: win32
  arch: x64
  PATH: C:\Program Files (x86)\Microsoft\Edge\Application;C:\Program Files\Microsoft Office\Root\Office16\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\PuTTY\;C:\Users\suseiler\AppData\Local\Microsoft\WindowsApps;C:\Users\suseiler\.dotnet\tools;C:\Users\suseiler\AppData\Roaming\npm;C:\Users\suseiler\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\suseiler\AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft Office\root\Client
  ```
  log:
  ```
  Attach Log file here - Found in: %temp%\Dev-Tools-Pack-Installer
  ```

**Comment by v-prsasa** [comment]
@v-robgi - Need your advice on the mentioned issue.

**Comment by v-robgi** [comment]
Need some more information here @saseiler - can you please attach the log file found under:

%temp%\Dev-Tools-Pack-Installer

Currently there isn't enough details here to move forward on.

@YifengZheng - can you please take care of the follow up?

**Comment by v-robgi** [comment]
[logs-192.zip](https://github.com/microsoft/Azure-Percept-Private-Preview/files/6423887/logs-192.zip)

**Comment by v-xiaoc** [comment]
The first two logs show no permissions, it should be that the UAC prompt is not approved. The following log shows that the docker.exe command cannot be found. I have found this bug before. After the installed of the new version of docker, the location of docker.exe file path has changed, and this problem has been solved .But this change is not yet pushed to the Blob.

**Comment by v-xiaoc** [comment]
@saseiler We have released the new version build to the studio. Please download and try again.

**Comment by v-iskha** [comment]
@saseiler - Hi Susan, since we do not have any update from you in last 7 days, we are assuming the issue to be fixed.
