### ISSUE TITLE
No status when applying firmware update

### ISSUE THREAD

**Issue by ckcampbell248** [microsoft/Azure-Percept-Private-Preview#194]
I'm trying to apply the firmware update via USB-C. 

-	I was able to connect with SSH and I am connected from my machine to the devkit via USB-C. 
-	I unzipped the firmware package and downloaded uuu into a folder on my local machine. 
-	I ran the uuu command and got the “Wait for known USB device to appear” message.
-	I ran the commands in the SSH shell to set the device to USB mode and reboot it. 
-	It appears to have rebooted. The power light is on but I have not received a message indicating success or failure. The power light flickers occasionally. It has been over 15 minutes with no status. How long should the device update take? 

After no status for over 15 minutes, I tried to SSH in from a separate terminal and found I could connect so I made the assumption that the update isn't working. I started the process again making sure to execute the uuu command before connecting over USB. I have the same result...no status. After another extended wait, I tried to SSH again and found I could not. 

The device went back into wifi access point mode. I connected to it's access point and opened a browser at 10.1.1.1 and was presented with the setup screen. Walking through the setup screen shows me that it still has settings for my home wifi network so I surmise that the firmware update has not completed. 

Can you help me get unblocked on the firmware update and get back to the initial setup state?

**Comment by v-iskha** [comment]
@ckcampbell248 - Hi Chris, first thing you need to check is that the USB cable is connected properly. Try unplugging and reconnecting both ends of the USB cable and jiggling the cable to ensure a secure connection. This almost always solves the issue.

Follow the below steps to update your dev kit:
•	[Instructions for how to update your dev kit over USB](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/private-preview-update-instructions.md)
•	[Instructions for connecting to your dev kit via SSH](https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/how-to-ssh.md)

**Comment by v-iskha** [comment]
@ckcampbell248 - Hi Chris, just following up on this. Did the instructions on the update worked for you?

**Comment by ckcampbell248** [comment]
I resolved this. I was trying to use uuu from a Linux shell on Windows Subsystem for Linux. When I switched to the Windows version of uuu from a Windows command prompt, it worked fine. I imagine the issue is with how WSL detects USB devices vs. Windows. You can close this but I would recommend updating the documentation to reference WSL.
