### ISSUE TITLE
azureeyemodule keep failing

### ISSUE THREAD

**Issue by MikeSpark** [microsoft/Azure-Percept-Private-Preview#195]
swVersion: 2021.105.111.112
vision module: 2104-2

Symptom: black screen on Webstream Video tab, azureeyemodule keep hitting error and restart module / reboot device does not work. Major error is Blocked event would cause dispatching thread to wait on semaphore infinitely. Tried to redeploy module in https://github.com/microsoft/Azure-Percept-Private-Preview/issues/191 but no luck

[percept15f_azureeyemodule_Logs.txt](https://github.com/microsoft/Azure-Percept-Private-Preview/files/6521536/percept15f_azureeyemodule_Logs.txt)

What had been done: deployed a custom vision project. Nothing special.

**Comment by MikeSpark** [comment]
I have new finding - things work as expected when I use another Percept Camera module from my teammate. How do I confirm it's HW failure? Thank you.

**Comment by v-iskha** [comment]
@MikeSpark - I would say, you can do device reset by re-flashing the latest firmware of the device and see if it fixes the issue. Sometimes it is the software which might create problem rather than hardware.

**Comment by MikeSpark** [comment]
@v-iskha already did, below is the device twins message

**Comment by v-iskha** [comment]
@MikeSpark - Yes I checked that your device is already having latest firmware. But the only way to reset the device is flashing the firmware again to reset everything on the device. Hence I recommended this.

**Comment by MikeSpark** [comment]
@v-iskha flashing again per https://docs.microsoft.com/en-us/azure/azure-percept/how-to-update-via-usb but no luck, exactly same error keep appearing

**Comment by mimcco** [comment]
@MikeSpark after updating your dev kit to the latest software, can you go through OOBE and add it as a new device in IoT Hub? Follow step 7 in these instructions: https://docs.microsoft.com/en-us/azure/azure-percept/quickstart-percept-dk-set-up.

I suspect you are trying to add the device you created when the dev kit was running the old software. We are aware of a bug that may cause the behavior you're experiencing. Creating a "new" device in IoT Hub should resolve it.

**Comment by MikeSpark** [comment]
@mimcco Well I did add it as a new device instead of reuse everytime I re-flashing the firmware. What I did not try is to use another IoT Hub, which I think does not make sense. Everytime I reset I will give it a newname on the IoT Hub so it knows it's brand new setup.

**Comment by tsampige** [comment]
@MikeSpark did you try to deploy another sample model from the percept studio and see if you are able to view the inference result in webstream?

**Comment by MikeSpark** [comment]
@tsampige yes I did. please find screenshot of failure FYI. 

![image](https://user-images.githubusercontent.com/8683422/119424571-4c3fcd00-bd38-11eb-8397-2518f72be5e5.png)

**Comment by MikeSpark** [comment]
Not sure does it count as finding but I re-flashed 3 times today, managed to get all modules running fine when camera module is not connected via USB. only when I connect the camera, the azureeyemodule will fail with same error

**Comment by v-iskha** [comment]
@tsampige - We have an update from Mike saying, "Not sure does it count as finding but I re-flashed 3 times today, managed to get all modules running fine when camera module is not connected via USB. only when I connect the camera, the azureeyemodule will fail with same error"

**Comment by tsampige** [comment]
@MikeSpark can you share the screenshot of the edge modules status from IoT Hub once the eye som is connected? What is the SW version of the firmware on the device after it was flashed?

**Comment by v-iskha** [comment]
@MikeSpark - Any update on the details asked by @tsampige ?

**Comment by tsampige** [comment]
@MikeSpark what is the status of the azureeyemodule in iothub? Here's the screenshot of where you can find the status
![image](https://user-images.githubusercontent.com/37117811/120521271-9d2f7100-c389-11eb-9712-7cab5d2cdbc1.png)

**Comment by MikeSpark** [comment]
after flashing the firmware, before plugin the physical camera, the azureeyemodule is shown as running, with version said something like "preload model", I tried both upgrade version or keep it preload, no matter which version of azureeyemodule, it fails after I plugin the physical camera. I highly suspsect something went wrong on camera itself and I can't restore the software by flashing the firmware. Error message stays the same.

**Comment by MikeSpark** [comment]
![image](https://user-images.githubusercontent.com/8683422/120590178-b3622d80-c46c-11eb-9a34-856d4ca62e5c.png)

**Comment by MikeSpark** [comment]
![image](https://user-images.githubusercontent.com/8683422/120590269-d7257380-c46c-11eb-98a6-9241b2bf2d8c.png)

**Comment by MikeSpark** [comment]
and then I click upgrade, as you may ask
![image](https://user-images.githubusercontent.com/8683422/120590911-da6d2f00-c46d-11eb-9807-e5cdc3f2c598.png)
waited a while, still the same result
![image](https://user-images.githubusercontent.com/8683422/120591122-359f2180-c46e-11eb-83a8-122908516efe.png)
I just paste the log here as well.
Inference App Version: 2021-02-08
2021-06-03 05:15:29 ERROR: Unrecognized string format for model data. Given a URL or zip or XML or blob file of path: 
2021-06-03 05:15:29 ERROR: Could not load the desired type of model. Using a default one instead.
2021-06-03 05:15:29 rm -rf /app/model && mkdir /app/model
2021-06-03 05:15:29 libusb_open_device_with_vid_pid VID 0x3e7 PID 0x2485 failed
2021-06-03 05:15:29 starting validator with VID 0x45e PID 0x66f
2021-06-03 05:15:29 authentication status: 0
SoM device is bound, devnode is /dev/bus/usb/001/003
2021-06-03 05:15:30 authentication status: 0
Start authentication
Sent connect request to SoM
Sent TLS data to SoM:2
Received TLS data from SoM: 160
Sent TLS data to service: 158
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
Received TLS data from SoM: 6
Tried to get TLS data from service: 3383
Get TLS data from Service: 3383
Sent TLS data to SoM:3383
2021-06-03 05:15:31 authentication status: 0
2021-06-03 05:15:32 authentication status: 0
Received TLS data from SoM: 77
Sent TLS data to service: 75
Received TLS data from SoM: 8
Sent TLS data to service: 6
Received TLS data from SoM: 47
Sent TLS data to service: 45
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
Received TLS data from SoM: 6
Tried to get TLS data from service: 1
Get TLS data from Service: 1
Sent TLS data to SoM:1
2021-06-03 05:15:33 authentication status: 0
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
Received TLS data from SoM: 6
Tried to get TLS data from service: 40
Get TLS data from Service: 40
Sent TLS data to SoM:40
Received TLS data from SoM: 105
Sent TLS data to service: 103
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
Received TLS data from SoM: 6
Tried to get TLS data from service: 28
Get TLS data from Service: 28
Sent TLS data to SoM:28
2021-06-03 05:15:34 authentication status: 0
Received TLS data from SoM: 199
Sent TLS data to service: 197
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
Received TLS data from SoM: 6
Tried to get TLS data from service: 3461
Get TLS data from Service: 3461
Sent TLS data to SoM:3461
Received TLS data from SoM: 675
Sent TLS data to service: 673
2021-06-03 05:15:35 authentication status: 0
2021-06-03 05:15:36 authentication status: 0
Received TLS data from SoM: 101
Sent TLS data to service: 99
2021-06-03 05:15:37 authentication status: 0
Received TLS data from SoM: 142
Sent TLS data to service: 140
Received TLS data from SoM: 32
Sent TLS data to service: 30
Received TLS data from SoM: 47
Sent TLS data to service: 45
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
Received TLS data from SoM: 6
Tried to get TLS data from service: 25
Get TLS data from Service: 25
Sent TLS data to SoM:25
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
2021-06-03 05:15:38 authentication status: 0
Received TLS data from SoM: 6
Tried to get TLS data from service: 40
Get TLS data from Service: 40
Sent TLS data to SoM:40
Received TLS data from SoM: 6
Tried to get TLS data from service: 5
Get TLS data from Service: 5
Sent TLS data to SoM:5
Received TLS data from SoM: 6
Tried to get TLS data from service: 595
Get TLS data from Service: 595
Sent TLS data to SoM:595
Received TLS data from SoM: 33
Sent TLS data to service: 31
Received TLS data from SoM: 2
Authentication Passed
2021-06-03 05:15:39 authentication status: 1
2021-06-03 05:15:39 RTSP thread created.
2021-06-03 05:15:39 Data collection thread created.
2021-06-03 05:15:39 rm -rf /app/snapshot/ && mkdir /app/snapshot/
2021-06-03 05:15:39 libusb_open_device_with_vid_pid VID 0x3e7 PID 0x2485 failed
2021-06-03 05:15:39 stream ready at rtsp://127.0.0.1:8554/raw
2021-06-03 05:15:39 stream ready at rtsp://127.0.0.1:8554/result
2021-06-03 05:15:39 stream ready at rtsp://127.0.0.1:8554/rawTCP
2021-06-03 05:15:39 stream ready at rtsp://127.0.0.1:8554/resultTCP
devnode: /dev/bus/usb/001/004, action: add
devnode: /dev/bus/usb/001/004, action: bind
2021-06-03 05:15:40 libusb_open_device_with_vid_pid VID 0x3e7 PID 0x2485 found
2021-06-03 05:15:40 Loading label file /app/data/labels.txt
2021-06-03 05:15:40 blobs: /app/data/ssd_mobilenet_v2_coco.blob, , firmware: /eyesom/mx.mvcmd, parser: SSD, label: /app/data/labels.txt, classes: 183
[36mI: [XLinkWrap] [    340745] [inference] boot:51	Initialized XLink component[0m
[36mI: [XLinkWrap] [    340746] [inference] boot:58	Found unbooted MX device name 1.1-ma2480[0m
[36mI: [XLinkWrap] [    341133] [inference] boot:66	MX device booted[0m
[33mW: [XLinkWrap] [    341133] [inference] boot:78	Failed to find MX booted device. Retrying...[0m
2021-06-03 05:15:41 module twin callback called with (state=DEVICE_TWIN_UPDATE_COMPLETE, size=159): {"desired":{"Logging":true,"ModelZipUrl":"","RawStream":true,"ResultStream":true,"Running":true,"TelemetryInterval":10,"$version":3},"reported":{"$version":1}}
2021-06-03 05:15:41 verbose_logging: 1
2021-06-03 05:15:41 raw_stream: 1
2021-06-03 05:15:41 result_stream: 1
[33mW: [XLinkWrap] [    341233] [inference] boot:78	Failed to find MX booted device. Retrying...[0m
devnode: /dev/bus/usb/001/004, action: unbind
devnode: /dev/bus/usb/001/004, action: remove
[33mW: [XLinkWrap] [    341333] [inference] boot:78	Failed to find MX booted device. Retrying...[0m
[33mW: [XLinkWrap] [    341434] [inference] boot:78	Failed to find MX booted device. Retrying...[0m
[33mW: [XLinkWrap] [    341534] [inference] boot:78	Failed to find MX booted device. Retrying...[0m
[33mW: [XLinkWrap] [    341634] [inference] boot:78	Failed to find MX booted device. Retrying...[0m
devnode: /dev/bus/usb/001/005, action: add
devnode: /dev/bus/usb/001/005, action: bind
[36mI: [XLinkWrap] [    341734] [inference] boot:82	Found booted MX with device name 1.1-
[0m
[36mI: [XLinkWrap] [    341739] [inference] boot:95	Successfully connected to Myriad device![0m
[37mD: [XLinkWrap] [    341740] [inference] boot:98	Exit with 0 (Success)[0m
[36mI: [VPUTempRead] [    341753] [inference] Init:44	Temperature reading initialized[0m
[36mI: [MxIf_InferBlock] [    342125] [inference] InferBlock:98	Send blob[0m
[33mW: [global] [    342165] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342237] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342273] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342309] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342380] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342416] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342489] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342525] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342598] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342634] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342742] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342784] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342815] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342850] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342888] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342958] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    342994] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343030] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343070] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343101] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343137] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343173] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343245] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343281] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343317] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343357] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343389] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
[33mW: [global] [    343424] [Scheduler00Thr] dispatcherLocalEventGetResponse:132	Blocked event would cause dispatching thread to wait on semaphore infinitely
[0m
2021-06-03 05:15:43 starting the pipeline...

**Comment by othmane-alaoui** [comment]
Hello @MikeSpark , I am having the same error. 
Have you found a solution?

**Comment by MikeSpark** [comment]
@othmane-alaoui No. still pending. Did you try using another Azure Eye?

**Comment by tsampige** [comment]
@MikeSpark i'm discussing with @mimcco to get you replacement devkit as i think there is an issue with the eye som cable connection.

**Comment by MikeSpark** [comment]
@tsampige thanks. any method we can capture the log from camera? I just worry other customers to run into same situation as well?

**Comment by tsampige** [comment]
@Devinwong Mike has a question about capturing log from camera. Are there any methods currently available?

**Comment by MikeSpark** [comment]
@tsampige any timeline can share for the replacement unit btw? Thank you

**Comment by tsampige** [comment]
@mimcco can you provide a rough timeline when Mike can expect replacement device?

**Comment by mimcco** [comment]
@MikeSpark, @tsampige - as discussed in our offline conversation, a new dev kit is on its way.
