### ISSUE TITLE
Upgrade instructions - wrong file

### ISSUE THREAD

**Issue by lokijota** [microsoft/Azure-Percept-Private-Preview#196]
The update instructions:
https://github.com/microsoft/Azure-Percept-Private-Preview/blob/main/update-your-devkit-today/private-preview-update-instructions.md

say to update with a file called xxx.2055.raw. However, the provided link is to a zip with version xxx.1825.raw .

**Comment by v-iskha** [comment]
@lokijota - The new updated file is 1.0.20210511.1825.zip

**Comment by v-iskha** [comment]
@lokijota - The GitHub page has been updated now reflecting new version. Thanks :)
